const tracks = [
    {
        id: 'ngot-lan-cuoi',
        title: 'Lần cuối',
        artist: 'Thắng và Ngọt Band',
        sourceFile: '/music/ngot-lan-cuoi.mp3',
        coverImage: '/img/ngot-lan-cuoi.webp',
    },
    {
        id: 'thuy-chi-que-toi',
        title: 'Quê Tôi',
        artist: 'Thùy Chi',
        sourceFile: '/music/thuy-chi-que-toi.mp3',
        coverImage: '/img/thuy-chi-que-toi.jpg',
    },
    {
        id: 'big-bang-haru-haru',
        title: 'Haru Haru',
        artist: 'Big Bang',
        sourceFile: '/music/big-bang-haru-haru.mp3',
        coverImage: '/img/big-bang-haru-haru.jpg',
    },
    {
        id: 'one-direction-what-makes-you-beautiful',
        title: 'What Makes You Beautiful',
        artist: 'One Direction',
        sourceFile: '/music/one-direction-what-makes-you-beautiful.mp3',
        coverImage: '/img/one-direction-what-makes-you-beautiful.jpg',
    },
    {
        id: 'justin-bieber-baby',
        title: 'Baby',
        artist: 'Justin Beiber',
        sourceFile: '/music/justin-bieber-baby.mp3',
        coverImage: '/img/justin-beiber-baby.jpeg',
    },
    {
        id: 'quang-le-xuan-nay-con-khong-ve',
        title: 'Xuân này con không về',
        artist: 'Quang Lê',
        sourceFile: '/music/quang-le-xuan-nay-con-khong-ve.mp3',
        coverImage: '/img/quang-le-xuan-nay-con-khong-ve.jpg',
    },
    {
        id: 'chuc-be-ngu-ngon',
        title: 'Chúc bé ngủ ngon',
        artist: 'VTV3',
        sourceFile: '/music/chuc-be-ngu-ngon.mp3',
        coverImage: '/img/chuc-be-ngu-ngon.webp',
    },
    {
        id: 'robo-trai-cay',
        title: 'Robo Trái Cây',
        artist: 'Hoạt hình tàu chiếu trên bibi',
        sourceFile: '/music/robo-trai-cay.mp3',
        coverImage: '/img/robo-trai-cay.webp',
    },
    {
        id: 'sieu-nhan-gao',
        title: 'Siêu nhân gao',
        artist: 'Đĩa lậu nhà hàng xóm bán',
        sourceFile: '/music/sieu-nhan-gao.mp3',
        coverImage: '/img/sieu-nhan-gao.webp',
    },
    {
        id: 'smoke-weed-everyday',
        title: 'Smoke Weed Everyday',
        artist: 'Snoop Dogg & Dr. Dre',
        sourceFile: '/music/smoke-weed-everyday.mp3',
        coverImage: '/img/smoke-weed-everyday.jpg',
    }
];
